services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: invima_fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./reports:/app/reports
    networks:
      - invima_network
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: invima_streamlit
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - FASTAPI_URL=http://fastapi:8000
    volumes:
      - ./streamlit_app:/app/streamlit_app
    depends_on:
      - fastapi
    networks:
      - invima_network
    restart: unless-stopped

networks:
  invima_network:
    driver: bridge
